export const FIGHT_STARTED = 'fight_started_event';
export const FIGHT_ENDED = 'fight_ended_event';
export const SOMEONE_GOT_HIT = 'someone_got_hit';
export const PLAYER_GOT_HIT = 'player_got_hit';
export const PLAYER_DIED = 'player_died';
export const MONSTER_DIED= 'monster_died';
export const MONSTER_GOT_HIT = 'monster_got_hit';
export const MAX_HIT = 99;
export const DELAY_PER_HIT = 1;
